package com.quarkdown.cli.creator.content

import com.quarkdown.cli.creator.template.ProjectCreatorTemplateProcessorFactory
import com.quarkdown.core.pipeline.output.OutputResource

/**
 * Supplier of the initial content of a new Quarkdown project.
 * This includes:
 * - Code content that goes into the main file
 * - Additional resources (e.g. assets)
 * @see com.quarkdown.cli.creator.ProjectCreator
 */
interface ProjectCreatorInitialContentSupplier {
    /**
     * @return the resource path of the precompiled `.jte` template whose output is inserted into the
     * main file (e.g. `"/creator/initialcontent.qd.jte"`). The template is rendered by the same
     * [com.quarkdown.core.template.TemplateProcessor] used by the
     * [com.quarkdown.cli.creator.ProjectCreator], so all placeholder injections set on the parent
     * template are available to it. If `null`, no code content is provided.
     *
     * The template must be precompiled at build time by the `gg.jte.gradle` plugin (i.e. live under
     * a `src/main/jte/...` directory), so rendering does not depend on the JDK compiler API and
     * works on a minimal jlink JRE.
     * @see ProjectCreatorTemplateProcessorFactory
     */
    val templateCodeContentResource: String?

    /**
     * @return a collection of additional resources that are generated by this supplier.
     * This may include assets, additional files, etc.
     */
    fun createResources(): Set<OutputResource>
}
